networks:
  web:

services:
  java-fcgi:
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - web
  nginx:
    build:
      context: ./frontend
    ports:
      - "9001:80"
    depends_on:
      - java-fcgi
    networks:
      - web